name: octree
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pylibtiff
  - dask=2021.10.0
  - dask-core=2021.10.0
  - dask-image=2021.12.0
  - dask-jobqueue=0.7.3
  - distributed=2021.10.0
  - numpy
  - pandas
  - scikit-image
  - tifffile
  - scipy
  - rasterio
  - pyopengl=3.1.1a1
